### ISSUE TITLE
Don't say that Messenger is not running, but run it instead

### ISSUE THREAD

**Issue by Philip-Scott** [aprilis/messenger#13]
Like the title says :) 

If you can start the popover with just the loading message, it would be a way better UX

**Comment by aprilis** [comment]
I really don't like the idea of this dialog, but I can't find a better solution. The problem is that when I run the app after activation from a chat icon, Plank associates any window opened by this process with that icon. It brings many problems, for instance when the main app window is opened and you click the chat icon, you can't view a chat bubble but Plank shows/hides the main window instead.
You can test it by commenting the `fake = true;` line in file Main.vala.
If you know any better workaround for this problem that would be great.

**Comment by Philip-Scott** [comment]
Try using Granite Application and filling in the results. Or maybe replace the dialog with a comand that launches the messenger process, and then ends. That way the main process would launch from outside of plank :) 

Here's an example to the application class: https://github.com/Philip-Scott/Spice-up/blob/master/src/Application.vala#L42

**Comment by aprilis** [comment]
I've managed to make a workaround using additional script which opens the app and then ends. Thanks!
