### ISSUE TITLE
2-step auth

### ISSUE THREAD

**Issue by MrVincs** [aprilis/messenger#5]
Hello,

I have problem when connect with my facebook account,
when i'm connecting to services, popup show 
"Do you use 2-step auth.. [Generate password]"

On my phone, i valide the session and browser but nothing change on app.

When i click [Generate password], window open with sms code verification, code validate, all is ok but no change on app..

Do you have issue with this or it's me ?

Sorry for my english ;D Vincs

**Comment by aprilis** [comment]
When you click "Generate password" it should open [this site](https://www.facebook.com/settings?tab=security&section=two_fac_auth&view) in your default browser. In section "App passwords" you can generate a password that you should copy&paste into the app (instead of your regular password). After that a window will appear when you have to login with your real password just like in a web browser. I know, it's too complicated. I'll simplify it as much as possible in the future

**Comment by MrVincs** [comment]
It Works !
Just put the sms code in password field and validate with facebook page, that's good!
Thanks a lot !
